"""
Symmetrization of a generic tensor to get a tensor with specific symmetry.
"""

import numpy as np


# TODO, this fn has the same name as one in the symmetrize.py file. We should
#  rename one of them
def symmetrize(t: np.ndarray, symmetry: str, mode: str = "mean") -> np.ndarray:
    """
    Symmetrize a generic tensor to obtain a tensor with the specified symmetry.

    This is achieved by pooling permutations of the tensor indices according to the
    the given symmetry.

    Args:
        t: The input tensor to be symmetrized.
        symmetry: The target symmetry of the output tensor. e.g. 'ijk=ikj=jik'.
        mode: The pooling operation to be used. Can be "mean" or "sum".

    Returns:
        The symmetrized tensor with the specified symmetry.
    """
    rank = len(t.shape)
    permutations = generate_permutations(symmetry)
    if len(permutations[0][0]) != rank:
        raise ValueError(f"Symmetry {symmetry} does not match tensor rank {rank}.")

    transformed = [
        sign * np.transpose(t, permutation) for permutation, sign in permutations
    ]
    if mode == "mean":
        return np.mean(np.stack(transformed), axis=0)
    elif mode == "sum":
        return np.sum(np.stack(transformed), axis=0)
    else:
        raise ValueError(f"Unknown pooling operation: {mode}. Use 'mean' or 'sum'.")


def check_symmetry(
    t: np.ndarray,
    symmetry: str,
    rtol: float = 1e-5,
    atol: float = 1e-7,
) -> bool:
    """
    Check if a tensor has the specified symmetry.

    Args:
        t: The input tensor to be checked.
        symmetry: The target symmetry of the output tensor. e.g. 'ijk=ikj=jik'.
        rtol: Relative tolerance used for numerical comparison.
        atol: Absolute tolerance used for numerical comparison. The default is loose
            enough for float32 tensors; tighten it for float64 ones.

    Returns:
        True if the tensor has the specified symmetry, False otherwise.
    """
    for permutation, sign in parse_symmetry_generators(symmetry, rank=t.ndim):
        if not np.allclose(
            np.transpose(t, permutation), sign * t, rtol=rtol, atol=atol
        ):
            return False
    return True


def generate_closure(generators: list[tuple[int, ...]]) -> list[tuple[int, ...]]:
    """
    Generate the closure of a set of permutations.

    Args:
        generators: A list of tuples representing the generator permutations. Each tuple
            is a permutation of indices.

    Returns:
        A list of all permutations generated by the input generators.
    """
    if not generators:
        return []
    seen = set(generators)
    queue = list(generators)

    while queue:
        p = queue.pop(0)
        for g in generators:
            # Compute g ∘ p: apply permutation g to the result of permutation p
            composed1 = tuple(g[i] for i in p)
            if composed1 not in seen:
                seen.add(composed1)
                queue.append(composed1)
            # Compute p ∘ g: apply permutation p to the result of permutation g
            composed2 = tuple(p[i] for i in g)
            if composed2 not in seen:
                seen.add(composed2)
                queue.append(composed2)

    return list(seen)


def generate_permutations(symmetry: str) -> list[tuple[tuple[int, ...], int]]:
    """
    Get index permutations for a specified tensor symmetry.

    This is the group closure of the generators returned by
    :func:`parse_symmetry_generators`, so it covers both symmetric and antisymmetric
    relations.

    Args:
        symmetry: A string representing the symmetry of the target tensor. For example,
            - "ij=ji" means that the target is a fully symmetric rank-2 tensor (e.g.
                stress tensor);
            - "ij=-ji" means that the target is an antisymmetric rank-2 tensor;
            - "ijk=ikj" means that the target is a rank-3 tensor with the last two
                indices symmetric (e.g. piezoelectric tensor);
            - "ijk=ikj=jik" means that the target is a fully symmetric rank-3 tensor;
            - "ijkl=jikl=klij" means that the target is a rank-4 tensor with both minor
                symmetry (between i and j, and between k and l) and major symmetry (
                between ij and kl). For example, the elastic tensor has this symmetry;
            The number of unique letters gives the rank of the tensor (what letters to
            use does not matter).
    Returns:
        ``(permutation, sign)`` pairs representing
        ``permute(tensor, permutation) = sign * tensor``.

    Raises:
        ValueError: If the relations assign conflicting signs to one permutation.
    """
    generators = parse_symmetry_generators(symmetry)
    rank = len(symmetry.split("=")[0].strip().replace(" ", ""))
    identity = tuple(range(rank))
    signs = {identity: 1}
    queue = [(identity, 1)]

    while queue:
        permutation, sign = queue.pop(0)
        for generator, generator_sign in generators:
            composed = tuple(generator[axis] for axis in permutation)
            composed_sign = sign * generator_sign
            if composed in signs:
                if signs[composed] != composed_sign:
                    raise ValueError("Inconsistent signed symmetry relations")
                continue
            signs[composed] = composed_sign
            queue.append((composed, composed_sign))

    return list(signs.items())


def parse_symmetry_generators(
    symmetry: str, rank: int | None = None
) -> list[tuple[tuple[int, ...], int]]:
    """Parse index equalities into signed permutation generators.

    Args:
        symmetry: Relations such as ``"ijk=ikj"`` or ``"ij=-ji"``. Every term is
            interpreted relative to the unsigned first term.
        rank: Expected tensor rank. If provided, it must match the number of indices
            in the reference term.

    Returns:
        ``(permutation, sign)`` pairs representing
        ``permute(tensor, permutation) = sign * tensor``.
    """
    parts = [part.strip().replace(" ", "") for part in symmetry.split("=")]
    if not parts or not parts[0] or parts[0].startswith(("+", "-")):
        raise ValueError("The first symmetry term must be an unsigned index string")

    original = parts[0]
    if len(set(original)) != len(original):
        raise ValueError("Each index must occur once in a symmetry term")
    if rank is not None and len(original) != rank:
        raise ValueError(f"Symmetry {symmetry} does not match tensor rank {rank}")
    index_to_axis = {char: axis for axis, char in enumerate(original)}

    generators = []
    for part in parts[1:]:
        sign = -1 if part.startswith("-") else 1
        term = part[1:] if part.startswith(("+", "-")) else part
        if len(term) != len(original):
            raise ValueError(f"Permutation {part} has wrong length")
        if set(term) != set(original):
            raise ValueError(f"Permutation {part} must contain the indices {original}")
        permutation = tuple(index_to_axis[char] for char in term)
        generators.append((permutation, sign))

    return generators


def get_random_tensor_of_symmetry(
    rank: int, symmetry: str, seed: int = 35
) -> np.ndarray:
    """
    Create a random tensor of the given rank and symmetry.
    """
    T = np.random.default_rng(seed).standard_normal((3,) * rank)
    T = symmetrize(T, symmetry)

    return T


if __name__ == "__main__":
    sym = "ij=ji"
    perms = generate_permutations(sym)
    print(f"perms for {sym}:\n", perms)

    sym = "ijk=jik=ikj"
    perms = generate_permutations(sym)
    print(f"perms for {sym}:\n", perms)

    sym = "ijkl=jikl=klij"
    perms = generate_permutations(sym)
    print(f"perms for {sym}:\n", perms)
