"""
Symmetrization of a generic tensor to get a tensor with specific symmetry.
"""

import torch
from torch import Tensor


# TODO, this fn has the same name as one in the symmetrize.py file. We should
#  rename one of them
def symmetrize(t: Tensor, symmetry: str, mode: str = "mean") -> Tensor:
    """
    Symmetrize a generic tensor to obtain a tensor with the specified symmetry.

    This is achieved by pooling permutations of the tensor indices according to the
    the given symmetry.

    Args:
        t: The input tensor to be symmetrized.
        symmetry: The target symmetry of the output tensor. e.g. 'ijk=ikj=jik'.
        mode: The pooling operation to be used. Can be "mean" or "sum".

    Returns:
        The symmetrized tensor with the specified symmetry.
    """
    rank = len(t.shape)
    indices = set(symmetry.replace(" ", "").replace("=", ""))
    if len(indices) != rank:
        raise ValueError(f"Symmetry {symmetry} does not match tensor rank {rank}.")

    perms = generate_permutations(symmetry)
    if mode == "mean":
        return torch.mean(torch.stack([torch.permute(t, p) for p in perms]), dim=0)
    elif mode == "sum":
        return torch.sum(torch.stack([torch.permute(t, p) for p in perms]), dim=0)
    else:
        raise ValueError(f"Unknown pooling operation: {mode}. Use 'mean' or 'sum'.")


def check_symmetry(t: Tensor, symmetry: str, rtol=1e-5, atol=1e-8) -> bool:
    """
    Check if a tensor has the specified symmetry.

    Args:
        t: The input tensor to be checked.
        symmetry: The target symmetry of the output tensor. e.g. 'ijk=ikj=jik'.

    Returns:
        True if the tensor has the specified symmetry, False otherwise.
    """
    perms = generate_permutations(symmetry)
    for perm in perms:
        if not torch.allclose(t, torch.permute(t, perm), rtol=rtol, atol=atol):
            return False
    return True


def generate_closure(generators: list[tuple[int, ...]]) -> list[tuple[int, ...]]:
    """
    Generate the closure of a set of permutations.

    Args:
        generators: A list of tuples representing the generator permutations. Each tuple
            is a permutation of indices.

    Returns:
        A list of all permutations generated by the input generators.
    """
    if not generators:
        return []
    seen = set(generators)
    queue = list(generators)

    while queue:
        p = queue.pop(0)
        for g in generators:
            # Compute g ∘ p: apply permutation g to the result of permutation p
            composed1 = tuple(g[i] for i in p)
            if composed1 not in seen:
                seen.add(composed1)
                queue.append(composed1)
            # Compute p ∘ g: apply permutation p to the result of permutation g
            composed2 = tuple(p[i] for i in g)
            if composed2 not in seen:
                seen.add(composed2)
                queue.append(composed2)

    return list(seen)


# TODO, generalize this handel inversion: e.g. "ijk=-jik"
def generate_permutations(symmetry: str) -> list[tuple[int, ...]]:
    """
    Get the index permutations for symmetrizing a generic tensor to obtain a tensor
    with the specified symmetry.

    Args:
        symmetry: A string representing the symmetry of the target tensor. For example,
            - "ij=ji" means that the target is a fully symmetric rank-2 tensor (e.g.
                stress tensor);
            - "ijk=ikj" means that the target is a rank-3 tensor with the last two
                indices symmetric (e.g. piezoelectric tensor);
            - "ijk=ikj=jik" means that the target is a fully symmetric rank-3 tensor;
            - "ijkl=jikl=klij" means that the target is a rank-4 tensor with both minor
                symmetry (between i and j, and between k and l) and major symmetry (
                between ij and kl). For example, the elastic tensor has this symmetry;
            The number of unique letters gives the rank of the tensor (what letters to
            use does not matter).

    Returns:
        A list of tuples representing the index permutations. All together, they can
        be used to symmetrize the tensor by some pooling operation such as sum or mean.
        For example, if symmetry is "ijk=ikj=jik", the output will be:
        [(0, 1, 2), (0, 2, 1), (1, 0, 2), (1, 2, 0), (2, 0, 1), (2, 1, 0)].
    """
    parts = [p.strip() for p in symmetry.split("=")]
    if len(parts) < 1:
        raise ValueError("Invalid symmetry rule. Use format `ij=ji`.")

    original = parts[0]
    index_to_axis = {char: idx for idx, char in enumerate(original)}

    # Get the generators for the permutations according to the symmetry
    generators = []
    for p in parts:
        if len(p) != len(original):
            raise ValueError(f"Permutation {p} has wrong length.")
        try:
            perm_tuple = tuple(index_to_axis[char] for char in p)
        except KeyError as e:
            raise ValueError(f"Index {e} not in original indices {original}.")
        generators.append(perm_tuple)

    # Generate all permutations from the generators
    perms = generate_closure(generators)

    return perms


def get_random_tensor_of_symmetry(rank: int, symmetry: str, seed: int = 35) -> Tensor:
    """
    Create a random tensor of the given rank and symmetry.
    """
    torch.manual_seed(seed)
    T = torch.randn((3,) * rank)
    T = symmetrize(T, symmetry)

    return T


if __name__ == "__main__":
    sym = "ij=ji"
    perms = generate_permutations(sym)
    print(f"perms for {sym}:\n", perms)

    sym = "ijk=jik=ikj"
    perms = generate_permutations(sym)
    print(f"perms for {sym}:\n", perms)

    sym = "ijkl=jikl=klij"
    perms = generate_permutations(sym)
    print(f"perms for {sym}:\n", perms)
